- name: Fetch Steam RSS feed
      run: |
        import feedparser
        import os
        from datetime import datetime
        import re

        def sanitize_filename(filename):
            return re.sub(r'[<>:"/\\|?*]', '', filename)

        feed_url = 'https://store.steampowered.com/feeds/news/app/2106670/?cc=US&l=english&snr=1_2108_9__2107'
        feed = feedparser.parse(feed_url)

        os.makedirs('content/PatchNotes', exist_ok=True)

        for entry in feed.entries:
            title = entry.title
            description = entry.description
            date_str = datetime.strptime(entry.published, '%a, %d %b %Y %H:%M:%S %Z')
            
            safe_title = sanitize_filename(title)
            file_name = f"content/PatchNotes/{safe_title}.md"

            # Create the frontmatter
            frontmatter = f'''---
link: {entry.link}
author: 
date: {date_str.strftime('%Y-%m-%dT%H:%M:%S')}
tags: []
---

'''
            file_content = frontmatter + f"# {title}\n\n{description}\n\nPublished on: {entry.published}"

            with open(file_name, 'w', encoding='utf-8') as f:
                f.write(file_content)
            
            print(f"Created file: {file_name}")
      shell: python
